services:
  backend:
    build: ./backend
    container_name: users-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    command: npm run start:prod
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: users-frontend
    ports:
      - '3001:3000'
    command: npm run start
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    env_file:
      - ./db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  adminer:
    image: adminer
    ports:
      - '8080:8080'

volumes:
  pgdata:
